Комментарий
htmlacademy-htmlcss/1481831-nerds-29 pull request #3
Opened 2020-09-22 14:56 UTC by HW2020370

Комментарий создан 2

2020-09-22 18:05 UTC, andreysgra requested changes
А в целом всё выполнено достаточно хорошо.

2020-09-22 18:05 UTC, andreysgra commented on catalog.html
> +      <p>191186, Санкт-Петербург,<br>ул. Б. Конюшенная, д. 19/8<br>тел. +7 (812) 275-75-75</p>
Вот эти элементы нужно обернуть в `div`

![image](https://user-images.githubusercontent.com/17790771/93919722-c1c14c80-fd16-11ea-9570-759f2b135a5b.png)

и разметить "Напишите нам" при помощи ссылки.

2020-09-23 14:03 UTC, HW2020370 commented on catalog.html
> +  </div>
> Непонятно, какой блок вы здесь разметили. Если это форма обратной связи, то размечать её сейчас не нужно

2020-09-23 14:04 UTC, HW2020370 commented on catalog.html
> +  </div>
Это всплывающее окно. Я его скопировала с главной страницы. Я так понимаю оно на всех страницах должно быть?

2020-09-23 20:08 UTC, andreysgra commented on catalog.html
> +  </div>
Это не модальное окно в привычном понимании. Этот блок является частью карточки товара. Изначально он скрыт и становится видимым по наведению курса мыши.

2020-09-23 20:13 UTC, HW2020370 commented
Андрей, это модальное окно, которое есть в футере главной страницы. А карточку товара я не оазмечада, позже сделаю.
--
Отправлено из Mail.ru для Android среда, 23 сентября 2020г., 23:09 +03:00 от Andrey Grachev  notifications@github.com :

>@andreysgra commented on this pull request.
>----------------------------------------------------------------------
>In  catalog.html :
> +  
>Напишите нам
>+  
>
>+      
>+    
>+  
>
>Это не модальное окно в привычном понимании. Этот блок является частью карточки товара. Изначально он скрыт и становится видимым по наведению курса мыши.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

2020-09-23 20:19 UTC, andreysgra approved these changes

2020-09-23 20:19 UTC, andreysgra commented on catalog.html
> +          <li><a href="index.html">Магазин</a></li>
```suggestion
          <li><a>Магазин</a></li>
```

2020-09-23 20:19 UTC, andreysgra commented on catalog.html
> +            <img src="#" alt="Sedona" />
В настоящее время не принято ставить слэш в конце непарного тега. Просто `<img src="#" alt="Sedona">`

2020-09-23 20:19 UTC, andreysgra commented on catalog.html
> +              Информационный сайт<br />
Аналогично: `<br>`.

2020-09-23 20:19 UTC, andreysgra commented on catalog.html
> +          </p>
![image](https://user-images.githubusercontent.com/17790771/93919722-c1c14c80-fd16-11ea-9570-759f2b135a5b.png)

Не виду в вашей разметке ссылки "Напишите нам".

2020-09-23 20:19 UTC, merged

2020-09-23 20:44 UTC, HW2020370 commented on catalog.html
> +          </p>
Андрей, я все исправила.