Стилизация главной страницы
htmlacademy-htmlcss/1481831-nerds-29 pull request #4
Opened 2020-09-26 13:44 UTC by HW2020370

2020-09-27 08:35 UTC, andreysgra requested changes
С форматированием кода совсем беда. Есть критерий [Б15](https://up.htmlacademy.ru/htmlcss/29/criteries#b15), который описывает единообразие оформления и форматирование кода. Нужно всё привести в порядок. Можно ориентироваться на [стиль кода Академии HTML](https://codeguide.academy/html-css.html). Также установите в свой редактор дополнение: для VS Code - **Beautify**, для Atom - **atom-beautify**. Оно позволяет форматировать код простым нажатием сочетаний клавиш: в VS Code это **Alt+Shift+F**, в Atom это  **Ctrl+Alt+B**.

2020-09-27 08:35 UTC, andreysgra commented on index.html
> +  <main main-class="center">
```suggestion
  <main class="center">
```

2020-09-27 08:35 UTC, andreysgra commented on index.html
> +    </div>
Похоже, что этот тег лишний.

2020-09-27 08:35 UTC, andreysgra commented on index.html
> +          <a class="button-red" href="#">Заказать</a>
Ссылка "Заказать" должна быть внутри `li`, а почему-то оказалась за его пределами.

2020-09-27 08:35 UTC, andreysgra commented on index.html
> +      </div>
А для чего это всё нужно?

2020-09-27 08:35 UTC, andreysgra commented on index.html
> +        <img src="img/index-logo.svg" width="156" height="65" alt="Logo" />
```suggestion
        <img src="img/index-logo.svg" width="156" height="65" alt="Logo">
```
В современном синтаксисе HTML слэш не ставится в конце непарного тега.

2020-09-27 08:35 UTC, andreysgra commented on index.html
> +          <h3 >Долго, дорогo, скрупулезно,</h3>
```suggestion
          <h3 >Долго, дорогo, скрупулезно.</h3>
```

2020-09-27 08:35 UTC, andreysgra commented on index.html
> +            Математически выверенный дизайн <br />
```suggestion
            Математически выверенный дизайн <br>
```

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +}
А зачем подключать шрифт через `@font-face` если вы уже подключили в `link` шрифт с Google Fonts? Нужно использовать что-то одно.

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +min-width: 1440px;
Минимальную ширину можно узнать из [Б13](https://up.htmlacademy.ru/htmlcss/29/criteries#b13). Для данного проекта она составляет 1200px.

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +padding: 0;
У `body` нет внутренних отступов изначально, поэтому нет смысла обнулять `padding`.

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +color: var(basic-white);
А зачем вы указываете три раза одно свойство с разными значениями? Браузер будет использовать то свойство, которое находится ниже, а остальные проигнорирует.

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +background:var(--basic-white);
Здесь тоже самое. Нужно оставить только один вариант.

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +}
Класс `.page-body` у вас применён к тегу `body`, а значит свойства описанные в селекторах `.page-body` и `body` будут применены к одному тегу - `<body>`.

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +nav.basket a:focus{
Если класс `.basket` используется только для стилизации ссылки корзины, то не нужно усложнять селектор. Но в вашей разметке я такого класса вообще не нашёл.

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +}
Класс `.visually-hidden` используется для доступного скрытия HTML элементов, а не для сброса маркеров у списка. Если вам про него ещё не рассказывали, то не нужно этот класс пока использовать. У него есть свой набор стилей.

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +.batton {
`button`, так ведь?

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +position: absolute;
А зачем нужно абсолютное позиционирование кнопке?

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +top: 922px;
Эти свойства тоже не нужны.

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +position: absolute;
Не нужно.

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +top: 922px;
Не нужно.

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +position: absolute;
Не нужно.

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +top: 922px;
Не нужно.

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +Line-height: 45px;
```suggestion
font-size: 45px;
line-height: 45px;
```

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +font-style: Regular;
У этого свойства такого значения нет https://webref.ru/css/font-style

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +line-height: 128%;
Давайте не будем задавать в процентах высоту линии.

2020-09-27 08:35 UTC, andreysgra commented on css/style.css
> +font-family: "Roboto";
Не нужно.

2020-09-29 07:57 UTC, andreysgra requested changes
Почему-то многие замечания не исправлены, а кроме этого появились новые.
Посмотрите заново все прошлые замечания которые я не пометил, как исправленные и устраните их.

Когда комментариев к пул реквест много, то Гитхаб часть из них скрывает за этой ссылкой:
![image](https://user-images.githubusercontent.com/17790771/94529200-1a767500-0242-11eb-9fd6-fcce62563ec6.png)

По поводу подключения шрифтов: должен использоваться только один из вариантов - либо с Google Fonts, либо локальное подключение, с помощью `@font-face`. Вы используете оба варианта.

2020-09-29 07:57 UTC, andreysgra commented on index.html
> +      <a class="basket"href="#">Корзина</a>
```suggestion
      <a class="basket" href="#">Корзина</a>
```

2020-09-29 07:57 UTC, andreysgra commented on css/style.css
> +  src: url("..//fonts/roboto.woff") format("woff2");
```suggestion
  src: url("../fonts/roboto.woff") format("woff");
```

2020-09-29 07:57 UTC, andreysgra commented on css/style.css
> +  src: url("..//fonts/robotobold.woff");
```suggestion
  src: url("../fonts/robotobold.woff2");
  src: url("../fonts/robotobold.woff");
```

2020-09-29 07:57 UTC, andreysgra commented on css/style.css
> +  src: url("..//fonts/robotomedium.woff");
```suggestion
  src: url("../fonts/robotomedium.woff2");
  src: url("../fonts/robotomedium.woff");
```

2020-09-29 07:57 UTC, andreysgra commented on css/style.css
> +  font-weight: medium;
Нет такого значения, как **medium**. Есть 500. И для единообразия оформления кода нужно привести к общему виду остальные значения: normal - 400, bold - 700.

2020-09-29 07:57 UTC, andreysgra commented on css/style.css
> +.social-icons-VK {}
```suggestion
.social-icons-vk {}
```

2020-09-29 07:57 UTC, andreysgra commented on css/style.css
> +.social-icons-VK {}
Селектор дублирует селектор в строке 293.

2020-09-29 07:57 UTC, andreysgra commented on css/style.css
> +.social-icons-FB {}
```suggestion
.social-icons-fb {}
```

2020-09-29 07:57 UTC, andreysgra commented on css/style.css
> +.social-icons-Ins {}
```suggestion
.social-icons-ins {}
```

2020-09-29 08:50 UTC, HW2020370 commented on css/style.css
> +}
Андрей, добрый день. Ну т.е. @font-face можно совсем убрать? Вы мне в прошлый раз писали, что нужно еще подключить шрифт 400 и 700. Посмотрите пожалуйста, в link  я это правильно сделала?

2020-09-29 08:53 UTC, HW2020370 commented on css/style.css
> +padding: 0;
Стилизацию показывали на примере Барбершопа, там стоит padding 0; Хорошо, уберу.

2020-09-29 19:41 UTC, HW2020370 commented on css/style.css
> +color: var(basic-white);
К какому тегу это относится? Удаляла строки из файла, теперь у меня не совпадает с тем, что здесь выложено

2020-09-29 19:50 UTC, andreysgra commented on css/style.css
> +padding: 0;
Это ошибка в демо.

2020-09-29 19:51 UTC, andreysgra commented on css/style.css
> +color: var(basic-white);
Поскольку вы до этого делали правки, то нумерация строк сбилась. Это относилось к тегу body.

2020-09-29 20:20 UTC, HW2020370 commented on index.html
> +      </div>
Это слайдер

2020-09-30 07:00 UTC, andreysgra commented on index.html
> +      </div>
Я понимаю, что это слайдер. Просто интересно, откуда вы взяли этот пример? (Спойлер: сейчас слайдеры на CSS не рассматриваются и данный код будет считаться ошибкой).

2020-09-30 07:01 UTC, andreysgra commented on css/style.css
> +}
Да, `@font-face` нужно убрать, если шрифт подключаете через Google Fonts.

2020-09-30 11:37 UTC, andreysgra requested changes
На этот раз почти всё хорошо. Но не исправлено 3 замечания первой проверки (смотрите в самом верху) и добавилось новое.

1. Подключение всех начертаний шрифта вы поправили в **index.html**, но не сделали в **catalog.html**.
2. Название файла **normalize** в **catalog.html** так и не исправили.
3. То, что вы разметили, как переключатели слайдов, нужно удалить (посмотрите мой ответ к комментарию).
4. Не забудьте исправить новое замечание по `font-family`.

2020-09-30 11:37 UTC, andreysgra commented on css/style.css
> +  font-family: "Roboto";
Во-первых, здесь альтернативные варианты шрифта. Во-вторых, `font-family` уже определён в `body`, а поскольку это свойств наследуемое, то его можно не указывать у остальных элементов (исключения составляют теги `button`, `input`, `textarea`).

2020-09-30 11:46 UTC, HW2020370 commented on index.html
> +      </div>
пример взяла из ютюба. Мне слайдер совсем удалить?

2020-09-30 11:48 UTC, HW2020370 commented on index.html
> +      </div>
А сейчас как делают слайдеры?

2020-09-30 11:49 UTC, HW2020370 commented on css/style.css
> +  font-family: "Roboto";
Хорошо, font-family уберу. Не исправила в catalog.html, потому что сейчас идет проверка главной страницы. Каталогом еще не занималась. Исправлю. Но в каталоге еще мног чего не сделано.

2020-10-01 08:38 UTC, merged